const { boolean } = require("joi");
const sequelize = require("./config");

const Gallery = sequelize.define('gallerys',{
    vendor_id:{
        type:Number,
        required:true
    },
    event_id:{
        type:String,
        required:true
    },
    description:{
       type:String,
       required:true
    },
    image_one:{
        type:String,
        required:true
     },
     image_two:{
        type:String,
        required:true
     },
     image_three:{
        type:Number,
        required:true
    },
    image_four:{
        type:String,
        required:true
    },
    image_five:{
        type:String,
        required:true
    },
    image_six:{
        type:String,
        required:true
    },
    image_seven:{
        type:String,
        required:true
    },
    video_one:{
        type:String,
        required:true
    },
    video_two:{
        type:String,
        required:true
    },
    is_active:{
        type:boolean,
        required:true
      },
      is_delete:{
        type:boolean,
        required:true
      },
});

module.exports=Gallery;